# Site settings
title: Lore-Leadership
email: contact@lore-leadership.com
description: An introduction to our vision and mission at Lore + Leadership> # this means to ignore newlines until "baseurl:"
baseurl: "lore-leadership" # the subpath of your site, e.g. /blog/
url: "https://www.lore-leadership.com"

#twitter_username:
#github_username:

# Build settings
markdown: kramdown
